### ISSUE TITLE
Can't find CUDA on Windows 11

### ISSUE THREAD

**Issue by Chadius** [rockerBOO/sd-webui-daam#12]
Hello rockerBOO. Thanks for porting this tool.

I can't get it to work on:
- Windows 11
- NVidia 4070 TI
- CUDA 118 installed and recognized by stable-diffusion-webui

I can run the daam-demo no problem, so I know the core library is working.

Using the cat example in the README, the cat renders properly but the attention images are blank. Additionally, when I start stable-diffusion the plugin seems to be looking for an .so file. I'm on Windows so I'd expect a dll (feel free to educate me on this one)

```
*** Error running install.py for extension C:\Users\there\Documents\stable-diffusion-webui\extensions\sd-webui-daam.
*** Command: "C:\Users\there\Documents\stable-diffusion-webui\venv\Scripts\python.exe" "C:\Users\there\Documents\stable-diffusion-webui\extensions\sd-webui-daam\install.py"
*** Error code: 1
*** stdout: False
***
*** ===================================BUG REPORT===================================
*** ================================================================================
*** The following directories listed in your path were found to be non-existent: {WindowsPath('/Program Files/Git/etc/config.site'), WindowsPath('C')}
*** The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
*** The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
*** The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
*** The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
*** The following directories listed in your path were found to be non-existent: {WindowsPath('C'), WindowsPath('/Program Files/Git/mingw64/include')}
*** The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
*** The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
*** CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
*** The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
*** DEBUG: Possible options found for libcudart.so: set()
*** CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
*** CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
*** CUDA SETUP: Loading binary C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
*** argument of type 'WindowsPath' is not iterable
*** CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
*** CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
*** CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
*** CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
*** CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
*** CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
*** CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
*** CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
*** CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
***
*** stderr: C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run
***
*** python -m bitsandbytes
***
***
***   warn(msg)
*** Traceback (most recent call last):
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 684, in _get_module
***     return importlib.import_module("." + module_name, self.__name__)
***   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
***     return _bootstrap._gcd_import(name[level:], package, level)
***   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 22, in <module>
***     from ..loaders import UNet2DConditionLoadersMixin
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\diffusers\loaders.py", line 28, in <module>
***     from .models.modeling_utils import _LOW_CPU_MEM_USAGE_DEFAULT, load_model_dict_into_meta
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 57, in <module>
***     import accelerate
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\accelerate\__init__.py", line 3, in <module>
***     from .accelerator import Accelerator
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 35, in <module>
***     from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
***     from .utils import (
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\__init__.py", line 131, in <module>
***     from .bnb import has_4bit_bnb_layers, load_and_quantize_model
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\bnb.py", line 42, in <module>
***     import bitsandbytes as bnb
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
***     from . import cuda_setup, utils, research
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
***     from . import nn
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
***     from .modules import LinearFP8Mixed, LinearFP8Global
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
***     from bitsandbytes.optim import GlobalOptimManager
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
***     from bitsandbytes.cextension import COMPILED_WITH_CUDA
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
***     raise RuntimeError('''
*** RuntimeError:
***         CUDA Setup failed despite GPU being available. Please run the following command to get more information:
***
***         python -m bitsandbytes
***
***         Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
***         to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
***         and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
***
*** The above exception was the direct cause of the following exception:
***
*** Traceback (most recent call last):
***   File "C:\Users\there\Documents\stable-diffusion-webui\extensions\sd-webui-daam\install.py", line 42, in <module>
***     if not check_daam():
***   File "C:\Users\there\Documents\stable-diffusion-webui\extensions\sd-webui-daam\install.py", line 31, in check_daam
***     import daam
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\daam\__init__.py", line 4, in <module>
***     from .hook import *
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\daam\hook.py", line 5, in <module>
***     from diffusers import UNet2DConditionModel
***   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 675, in __getattr__
***     value = getattr(module, name)
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 674, in __getattr__
***     module = self._get_module(self._class_to_module[name])
***   File "C:\Users\there\Documents\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 686, in _get_module
***     raise RuntimeError(
*** RuntimeError: Failed to import diffusers.models.unet_2d_condition because of the following error (look up to see its traceback):
***
***         CUDA Setup failed despite GPU being available. Please run the following command to get more information:
***
***         python -m bitsandbytes
***
***         Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
***         to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
***         and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

Does DAAM rely on bitsandbytes? If so I'll try to get that fixed first.

**Comment by rockerBOO** [comment]
Which version of the a1111 is this? 1.7? 

I am fairly certain it doesn't use bitsandbytes so not sure why it's infering that, but maybe some newer version of diffusers is getting installed which happens to require it now? Regardless I am not needing it for the daam library so we can probably get it to install an appropriate version of diffusers if necessary.

**Comment by Chadius** [comment]
Yes, this is a1111 Stable-Diffusion 1.7. Sounds like bitsandbytes might be a red herring. I'm currently using diffusers 0.18.2 .

Thanks for the response!

**Comment by rockerBOO** [comment]
I have this `diffusers >= 0.21, < 1.0` for daam so would make sure you're using that version at least. I would imagine it would try to install at least 0.21 but maybe my install script is not working properly. Let me know if you find anything though.

**Comment by Chadius** [comment]
Okay, so I upgraded diffusers to 0.21.4 .
I disabled every extension and I'm still getting this error. I think this all a bitsandbytes issue. I can't even restart sd.
I'll look into bitsandbytes for now. Thanks for helping me narrow down what's going on.

**Comment by Chadius** [comment]
Update: It's SDXL, I'm getting blank images when I switch to an SDXL checkpoint. The standard 1.5-pruned works like a charm.
